packages:
  - 'packages/*'

verifyDepsBeforeRun: false

overrides:
  '@babel/runtime': 7.28.6
  '@floating-ui/core': 1.7.5
  '@floating-ui/dom': 1.7.6
  '@floating-ui/react-dom': 2.1.8
  '@floating-ui/utils': 0.2.11

allowBuilds:
  '@parcel/watcher': true
  core-js: false
  esbuild: true
  sharp: true
  workerd: true
